config/routes.rb
Rails.application.routes.draw do

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  
  get 'favorite_car', to: 'saved_cars#favorite_car', as: 'favorite_car'
  get 'car_details/:id/saved_car', to: 'saved_cars#save_car', as: 'saved_car'
  get 'about', to: 'homes#about', as: 'about'


  root to: 'homes#welcome'
  get 'dashboard', to: 'dashboards#dashboard', as:'dashboard'
  get 'profile', to: 'users#profile', as: 'profile'  # profile
  get 'home', to: 'homes#welcome', as:'home'
  #get 'car_details', to: 'cars#index', as: 'car_details' # car details
  get 'car_details/:id', to: 'cars#car_details', as:'car_details'

  get 'car_details/:id/edit', to: 'cars#edit', as: 'update_car'
  put 'car_details/:id', to: 'cars#update' # update (put)
  patch 'car_details/:id', to: 'cars#update' # update (patch)

  # Navid
  # get 'users/:id/edit_password', to: 'users#edit_password', as: 'change_password' # edit
  # patch 'users/:id', to: 'users#update_password' # update (as needed)
  # put 'users/:id', to: 'users#update_password' # update (full replacement)

  # Hosneara: added routes for delete car # 
  get 'car_details/:id/confirm_delete', to: 'cars#delete_car', as: 'delete_car'
  delete 'car_details/:id/confirm_delete', to: 'cars#destroy'
  #get 'car_details/:id/delete_car_image', to: 'cars#delete_car_image', as: 'delete_car_image'
  
  get 'send_message_to_seller/:id', to: 'conversations#send_message_to_seller', as:'send_message_to_seller'
  get 'send_message', to: 'conversations#index', as: 'send_message'
  get 'notification/:id', to: 'notifications#show', as: 'notification'

  get 'new_conversation/:id', to: 'conversations#new_conversation', as: 'new_conversation'

  post 'new_message', to: 'messages#new_message', as: 'new_message'

  get 'report', to: 'users#report', as: 'report'
  post 'report', to: 'users#report_authority', as: 'report_authority'
  get 'view_report', to: 'users#index', as: 'view_report'
  get 'authority_view', to: 'users#authority_view', as: 'authority_view'

  get 'search', to: 'homes#search', as:'search'
  get 'advance_search', to: 'homes#advance_search', as:'advance_search'
  
  get 'upload_car', to: 'cars#upload_car', as: 'upload_car'
  post 'upload_car', to: 'cars#upload_car_form', as: 'upload_car_form'

  post 'rate_this_seller', to: 'cars#rate_this_seller', as: 'rate_this_seller'
  post 'mark_as_sold', to: 'cars#mark_as_sold', as:'mark_as_sold'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  authority              :boolean
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string
#  phone_no               :string
#  rating                 :float            default(0.0)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  uid                    :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :cars, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :saved_cars, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # For default user icon
  after_commit :add_default_photo, on: [:create, :update]
  private def add_default_photo
    unless photo.attached?
      self.photo.attach(io: File.open(Rails.root.join("app", "assets", "images", "user.png")), filename: 'user.png' , content_type: "image/jpg")
    end
  end

  validate :uid_must_begin_with_U_and_length_should_be_nine
  validate :email_must_be_of_uofm
  validates :uid, presence: true
  validates_uniqueness_of :uid, :allow_blank => true, :allow_nil => true

  def uid_must_begin_with_U_and_length_should_be_nine
    if !uid.empty?
      if !uid.start_with?("U") || uid.length>9
        errors.add(:uid, " is not valid")      
      end
    end
  end

  def email_must_be_of_uofm
    if !email.empty? && !email.end_with?("memphis.edu")
      errors.add(:email, " is not of UofM")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def profile
    user_id = current_user.id
    user_ratings = Rating.where(seller_id: user_id).sum(:rating)
    totalRater = Rating.select(:id).where(seller_id: user_id).count
    respond_to do |format|
        if totalRater != 0
          averageRating = user_ratings.to_f/totalRater.to_f
        else
          averageRating = 0.0
        end
        format.html { render :profile, locals:{user_rating: averageRating.round} }
    end
  end

  def report
    respond_to do |format|
      format.html do
        render :report
      end
    end
  end

  def report_authority
    report_data = Report.new(params.require(:report).permit(:subject, :body, :user_id))
    authority = User.where("authority = ?", true)
    reports = Report.where(user_id: report_data.user_id)
    respond_to do |format|
        format.html do
          if report_data.save
            flash[:success] = "Thank you for your feedback. We will take care of it."
            render :show, locals: { reports: reports }
          else
            flash[:warning] = "Error! couldn't report this time. Please try again!"
          end
        end
    end
  end

  def index
    reports = Report.where(user_id: current_user.id)
    respond_to do |format|
      format.html do
        render :show, locals: { reports: reports }
      end
    end
  end

  def authority_view
    reports = Report.all
    respond_to do |format|
      format.html do
        render :show, locals: { reports: reports }
      end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.erb
<div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <div class="row">
        <div class="col-sm-4 d-flex flex-row-reverse">
          <span class="text-primary font-weight-bold h2">User Profile</span>
        </div>
        <div class="col-sm-8"></div>
      </div>
      <div class="row">
        <div class="col-sm-5">
          <div class="profile-header-container">   
    		      <div class="profile-header-img">
                <%= image_tag(current_user.photo, class:'img-circle') %>
            </div>
          </div> 
        </div>

        <div class="col-sm-1 vertical_bar"></div>

        <div class="col-sm-6">
          <div class="row profileMartingTop">
            <div class="col-sm-3 d-flex flex-row-reverse"><span class="font-weight-bold">Name:</span></div>
            <div class="col-sm-9 underline_profile_text"><%= current_user.name %></div>
          </div>
          <div class="row profileMartingTop">
            <div class="col-sm-3 font-weight-bold float-right d-flex flex-row-reverse">Email:</div>
            <div class="col-sm-9 underline_profile_text"><%= current_user.email %></div>
          </div>
          
          <div class="row profileMartingTop">
            <div class="col-sm-3 font-weight-bold float-right d-flex flex-row-reverse">Phone No:</div>
            <div class="col-sm-9 underline_profile_text"><%= current_user.phone_no %></div>
          </div>

          <div class="row profileMartingTop">
            <div class="col-sm-3 font-weight-bold float-right d-flex flex-row-reverse">UID:</div>
            <div class="col-sm-9 underline_profile_text"><%= current_user.uid %></div>
          </div>
          <div class="row profileMartingTop">
            <div class="col-sm-3 font-weight-bold float-sm-right d-flex flex-row-reverse">Rating:</div>
            <div class="col-sm-9">
              <% (1..user_rating).each do |i|%>
                <i class="fa fa-star" style="color:red"></i>
              <% end %>
              <% (user_rating+1..5).each do |i|%>
                <i class="fa fa-star-o" style="color:red"></i>
              <% end %>
            
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4 d-flex flex-row-reverse"></div>
        <div class="col-sm-4 d-flex flex-row-reverse">
          <%= link_to 'Update Profile', edit_user_registration_path, class:'btn btn-success btn_radius' %>
        </div>
        <div class="col-sm-4 d-flex flex-row-reverse"><%= link_to "Delete Account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete, class:'btn btn-danger btn_radius' %></div>
      </div>
    </div>
    <div class="col-sm-1"></div>
</div>

app/views/users/report.html.erb
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-9">
        <%= form_with url: report_authority_path, method: :post, local: true, scope: :report do |f| %>  
            <div class="form-group">
                <strong><%= f.label "Report to" %></strong>
                <%= content_tag :p, class: "form-control" do -%>
                    <%= link_to 'mailto:report@memphis.edu', '' %>
                <% end -%>
            </div>
            
            <div class="form-group">
                <strong><%= f.label "subject" %></strong>
                <%= f.text_area "subject", size: "5x1" , :class => 'form-control', :placeholder => "I want to report because...", required: true %>
            </div>

            <div class="form-group">
                <strong><%= f.label "message" %></strong>
                <%= f.text_area "body", size: "5x5" , :class => 'form-control', :maxlength => 500,
                :placeholder => "Type your message (Max 500 characters)", required: true%>
            </div>
            
            <div class="form-group">
                <%= f.text_field :user_id, value: current_user.id, type: "hidden"%>
            </div>
            
            <div class="form-group row">
                <div class="col-md-4">
                    <%= f.submit "Send", :class=>"btn btn-success btn-block"%>
                </div>
                <div class="col-md-4">
                    <%= link_to 'Past reports', view_report_path, :class=> "btn btn-info btn-block" %>
                </div>
                <div class="col-md-4">
                    <%= link_to 'Back to home', home_path, :class=> "btn btn-primary btn-block" %>
                </div>
                
            </div>
        <% end %>
    </div>
    <div class="col-md-1"></div>
</div>

app/views/users/send_message.html.erb
<%= form_with url: send_message_path, local: true, method: :get do %>
    <div class="form-group">
        <div class="form-group">
            <label for="message_to">Message to</label>
            <%
                i = 0
                user_array = Array.new()
                @users.each do |user|
                        user_array.insert(i, user.email)
                        i=i+1
                end
            %>
            <%= select_tag "message_to", 
            options_for_select(user_array), prompt: '---Send to---' , class:"form-control"%>
        </div>
    </div>
    <div class="form-group">
        <label for="message">Message</label>
        <textarea class="form-control" id="message_body" rows="3" placeholder="Type your message here..."></textarea>
    </div>
    <div class="col text-center">
        <button class="btn btn-primary" data-target="#new">Send</button>
         <li><button type="button" class="list-group-item"
    data-toggle="collapse" data-target="#new"><h4>New Message
      <i class="glyphicon glyphicon-new-window" style="vertical-align:right;"></i></h4></button></li>
    </div>
    
    <div id="new" class="collapse">
    <div class="panel-body">
     <h1 class="panel-heading">All Users:</h1>
       <% @users.each do |user| %>
            <div class="item">
                <h3>
                    <%= link_to user.email,
                    conversations_path(sender_id: current_user.id, recipient_id: user.id), method: "post"%>
                </h3>
            </div>
     <% end %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="row">
<div class=col-md-1></div>
<div class="col-md-10">
    <div class= "display-message col-md-12">
    <% if !reports.empty? %>
        <table class="table table-striped table-bordered">
            <tbody>
                <% reports.each do |report| %>
                    <tr>
                        <td>
                        <% if current_user.authority %>
                            <h4><strong>Reporter: <%= User.find(report.user_id).email %></strong></h4>
                        <% end %>
                        <h5><strong><%= report.message_time %></strong></h5>
                        <h6><strong>Subject: </strong><%= report.subject %></h6>
                        <h6><strong>Message: </strong><%= report.body %></h6>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    <% end %>
    <% if reports.length == 0 %>
        <% if !current_user.authority %>
            <h2 style="text-align: center;"><strong> You did not report any seller <strong></h2>
        <% else %>
            <h2 style="text-align: center;"><strong> No one reported yet <strong></h2>
        <% end %>
    <% end %>
    </div>
    <div style="text-align: center;">
        <%= link_to 'Back to home', home_path, :class=> "btn btn-primary" %>
    </div>
</div>
<div class=col-md-1></div>
</div>