config/routes.rb
Rails.application.routes.draw do

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  
  get 'favorite_car', to: 'saved_cars#favorite_car', as: 'favorite_car'
  get 'car_details/:id/saved_car', to: 'saved_cars#save_car', as: 'saved_car'
  get 'about', to: 'homes#about', as: 'about'


  root to: 'homes#welcome'
  get 'dashboard', to: 'dashboards#dashboard', as:'dashboard'
  get 'profile', to: 'users#profile', as: 'profile'  # profile
  get 'home', to: 'homes#welcome', as:'home'
  #get 'car_details', to: 'cars#index', as: 'car_details' # car details
  get 'car_details/:id', to: 'cars#car_details', as:'car_details'

  get 'car_details/:id/edit', to: 'cars#edit', as: 'update_car'
  put 'car_details/:id', to: 'cars#update' # update (put)
  patch 'car_details/:id', to: 'cars#update' # update (patch)

  # Navid
  # get 'users/:id/edit_password', to: 'users#edit_password', as: 'change_password' # edit
  # patch 'users/:id', to: 'users#update_password' # update (as needed)
  # put 'users/:id', to: 'users#update_password' # update (full replacement)

  # Hosneara: added routes for delete car # 
  get 'car_details/:id/confirm_delete', to: 'cars#delete_car', as: 'delete_car'
  delete 'car_details/:id/confirm_delete', to: 'cars#destroy'
  #get 'car_details/:id/delete_car_image', to: 'cars#delete_car_image', as: 'delete_car_image'
  
  get 'send_message_to_seller/:id', to: 'conversations#send_message_to_seller', as:'send_message_to_seller'
  get 'send_message', to: 'conversations#index', as: 'send_message'
  get 'notification/:id', to: 'notifications#show', as: 'notification'

  get 'new_conversation/:id', to: 'conversations#new_conversation', as: 'new_conversation'

  post 'new_message', to: 'messages#new_message', as: 'new_message'

  get 'report', to: 'users#report', as: 'report'
  post 'report', to: 'users#report_authority', as: 'report_authority'
  get 'view_report', to: 'users#index', as: 'view_report'
  get 'authority_view', to: 'users#authority_view', as: 'authority_view'

  get 'search', to: 'homes#search', as:'search'
  get 'advance_search', to: 'homes#advance_search', as:'advance_search'
  
  get 'upload_car', to: 'cars#upload_car', as: 'upload_car'
  post 'upload_car', to: 'cars#upload_car_form', as: 'upload_car_form'

  post 'rate_this_seller', to: 'cars#rate_this_seller', as: 'rate_this_seller'
  post 'mark_as_sold', to: 'cars#mark_as_sold', as:'mark_as_sold'

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def welcome
    respond_to do |format|
      cars = Car.all
      makes = Car.distinct.pluck(:make)
      models = Car.distinct.pluck(:model)
      mileages = Car.distinct.pluck(:mileage)
      years = Car.distinct.pluck(:year)
      prices = Car.distinct.pluck(:price)
      format.html do 
        render :welcome, locals:{search_result: cars,makes:makes, models:models, mileages:mileages,years:years, prices:prices,is_search:false}
      end
    end
  end

  def search
    respond_to do |format|
      makes = Car.distinct.pluck(:make)
      models = Car.distinct.pluck(:model)
      mileages = Car.distinct.pluck(:mileage)
      years = Car.distinct.pluck(:year)
      prices = Car.distinct.pluck(:price)
      format.html do
        if params[:search].blank?
          search_result = "Empty! Please try again!"
          render :welcome, locals:{search_msg: search_result ,makes:makes, models:models, mileages:mileages,years:years, prices:prices, is_search:true}
        else
          search_result = Car.where(make: params[:search].downcase)
          render :welcome, locals:{search_result: search_result,makes:makes, models:models, mileages:mileages,years:years, prices:prices,is_search:true}
        end
      end
    end
  end
  
  def advance_search
    respond_to do |format|
      makes = Car.distinct.pluck(:make)
      models = Car.distinct.pluck(:model)
      mileages = Car.distinct.pluck(:mileage)
      years = Car.distinct.pluck(:year)
      prices = Car.distinct.pluck(:price)
      empty ||=check_empty 
      format.html do
        if empty
          search_result = "Empty! Please try again!"
          render :welcome, locals:{search_msg: search_result ,makes:makes, models:models, mileages:mileages,years:years, prices:prices, is_search:true}
        else
          search_result = Car.order(id: :asc)
          search_result = search_result.where(make: params[:make].downcase) if params[:make].present?
          search_result = search_result.where(model: params[:model].downcase) if params[:model].present?
          search_result = search_result.where(mileage: params[:mileage]) if params[:mileage].present?
          search_result = search_result.where(year: params[:year]) if params[:year].present?
          search_result = search_result.where(price: params[:price]) if params[:price].present?
          render :welcome, locals:{search_result: search_result,makes:makes, models:models, mileages:mileages,years:years, prices:prices,is_search:true}
        end 
      end
    end
  end
  private def check_empty
    empty = true
    params.each do |key, value|
      if key.eql? "make" or key.eql? "model" or key.eql? "mileage" or key.eql? "year" or key.eql? "price" and !value.empty?
        empty = false
      end
    end
    return empty
  end

  def message
    respond_to do |format|
      format.html { render :message }
    end
  end

  def about
    respond_to do |format|
      format.html { render :about }
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="row">
  <div class='col-md-3'></div>
    <div class='col-md-7'>

    <h1>Tiger-Car-App</h1>
    <p style="margin-bottom:1cm;"></p>
    <p>Many students at UofM want to buy a car but they do not know where to get a good car at an affordable price.
    On the other hand , many UofM students want to sell their car before leaving campus but cant find a reliable source to sell their car. This web platform will enable
    both buyer/seller to fullfil their needs. Most of the students also have financial constraints while buying a car.
    Since many of the sellers will be from UofM , it will be easier for both parties to buy/sell a car with limited
    budget constraints. It will also be easier to meetup for both parties if they are from UofM . They can meet on
    campus without having to go someplace far away.<p>
    <p>Students will be registered into the system with their unique UofM ID and password . So any fraudulent activity can
    be easily tracked. Students can report any issues to the campus authority if anything suspicious happens.</p>

    </div>
  <div class="col-md-3"></div>
</div>

app/views/homes/welcome.html.erb
  
<div class="row" style="margin-top: 20px">
    <div class="col-md-6 justify-content-center align-items-around">
        <!-- Search form -->
        <%= form_with url: search_path, local: true, method: :get do %>
            <div class="input-group mb-4 border rounded-pill p-2">
                <div class="input-group-prepend border-0">
                    <%= button_tag type: 'submit', class: "btn btn-link text-info", id: "button-addon4" do %>
                        <i class="fa fa-search" aria-hidden="true"></i>
                    <% end %>
                </div>

                <%= search_field_tag :search, params[:search], placeholder:"Search cars by make........", class: "form-control bg-none border-0"%>
            </div>
        <%end%>

        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-6">
                <% if local_assigns.has_key? :search_msg %>
                    <p class="alert alert-warning"><%= search_msg %></p>
                <% end %>
            </div>
            <div class="col-md-2">
            </div>
        </div>
    </div>
    <div class="col-md-6 border">
        <span class="advanceSearch"> Advance Search</span>
        <%= form_with url: advance_search_path, local: true, method: :get do %>
            <div class="form-group">
                <%
                i = 0
                makes_array = Array.new()
                if !makes.empty?
                    makes.each do |make|
                        makes_array.insert(i, make.upcase)
                        i=i+1
                    end
                end
                %>
                <%= select_tag "make", options_for_select(makes_array), prompt: 'Make...' , class:"form-control"%>
                
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <%
                    i = 0
                    makes_array = Array.new()
                    if !models.empty?
                        models.each do |model|
                            makes_array.insert(i, model.upcase)
                            i=i+1
                        end
                    end
                    %>
                    <%= select_tag "model", options_for_select(makes_array), prompt: 'Model...' , class:"form-control"%>

                </div>
                <div class="form-group col-md-6">
                    <%
                    i = 0
                    makes_array = Array.new()
                    if !mileages.empty?
                        mileages.each do |mileage|
                            makes_array.insert(i, mileage)
                            i=i+1
                        end
                    end
                    %>
                    <%= select_tag "mileage", options_for_select(makes_array), prompt: 'Mileage...' , class:"form-control"%>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <%
                    i = 0
                    makes_array = Array.new()
                    if !years.empty?
                        years.each do |year|
                            makes_array.insert(i, year)
                            i=i+1
                        end
                    end
                    %>
                    <%= select_tag "year", options_for_select(makes_array), prompt: 'Year...' , class:"form-control"%>
                </div>
                <div class="form-group col-md-6">
                    <%
                    i = 0
                    makes_array = Array.new()
                    if !prices.empty?
                        prices.each do |price|
                            makes_array.insert(i, price)
                            i=i+1
                        end
                    end
                    %>
                    <%= select_tag "price", options_for_select(makes_array), prompt: 'Price...' , class:"form-control"%>
                </div>
            </div>
  
            <div class="form-row">
                <div class="form-group col-md-4"></div>
                <div class="form-group col-md-4">
                    <%= submit_tag "Search", class:"form-control"%>
                </div>
                <div class="form-group col-md-4"></div>
            </div>
        <%end%>
    </div>
</div>
<div class="row" style="margin-top:20px">
    <div class="col-md-12">
        <% if is_search%>
        <span class="font-weight-bold"> Search Results</span>
        <%else%>
            <span class="font-weight-bold"> Featured Cars</span>
        <%end%>
    </div>
    <% if local_assigns.has_key? :search_result and !search_result.empty?%>
    <div class="col-md-12">
        <div class="row">
            <% search_result.each do |car|%>
            <div class="col-md-3">
                <div clas="row">
                    <div class="col-md-7">
                        <label class="text-center"> <%= car.make.upcase %> <%= car.model.upcase %></label>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-7">
                        <%= image_tag(car.image,class:'car_size') %>
                    </div>
                    <div class="col-md-4">
                        <p>Year:<%= car.year %></p>
                        <p>Mileage:<%= car.mileage %></p>
                        <p>Price:$<%= car.price %></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-7 justify-content-center">
                        <%= link_to 'View Details', car_details_path(car), class:'btn  btn-viewDetails' %>
                    </div>
                </div>
            </div>
            <%end%>

        </div>
    </div>
    <% else %>

    <div class="col-md-12">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <p class="text-danger"> No Car found!</p>
        </div>
        <div class="col-md-3"></div>
    </div>

    <%end%>
</div>