config/routes.rb
Rails.application.routes.draw do

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  
  get 'favorite_car', to: 'saved_cars#favorite_car', as: 'favorite_car'
  get 'car_details/:id/saved_car', to: 'saved_cars#save_car', as: 'saved_car'
  get 'about', to: 'homes#about', as: 'about'


  root to: 'homes#welcome'
  get 'dashboard', to: 'dashboards#dashboard', as:'dashboard'
  get 'profile', to: 'users#profile', as: 'profile'  # profile
  get 'home', to: 'homes#welcome', as:'home'
  #get 'car_details', to: 'cars#index', as: 'car_details' # car details
  get 'car_details/:id', to: 'cars#car_details', as:'car_details'

  get 'car_details/:id/edit', to: 'cars#edit', as: 'update_car'
  put 'car_details/:id', to: 'cars#update' # update (put)
  patch 'car_details/:id', to: 'cars#update' # update (patch)

  # Navid
  # get 'users/:id/edit_password', to: 'users#edit_password', as: 'change_password' # edit
  # patch 'users/:id', to: 'users#update_password' # update (as needed)
  # put 'users/:id', to: 'users#update_password' # update (full replacement)

  # Hosneara: added routes for delete car # 
  get 'car_details/:id/confirm_delete', to: 'cars#delete_car', as: 'delete_car'
  delete 'car_details/:id/confirm_delete', to: 'cars#destroy'
  #get 'car_details/:id/delete_car_image', to: 'cars#delete_car_image', as: 'delete_car_image'
  
  get 'send_message_to_seller/:id', to: 'conversations#send_message_to_seller', as:'send_message_to_seller'
  get 'send_message', to: 'conversations#index', as: 'send_message'
  get 'notification/:id', to: 'notifications#show', as: 'notification'

  get 'new_conversation/:id', to: 'conversations#new_conversation', as: 'new_conversation'

  post 'new_message', to: 'messages#new_message', as: 'new_message'

  get 'report', to: 'users#report', as: 'report'
  post 'report', to: 'users#report_authority', as: 'report_authority'
  get 'view_report', to: 'users#index', as: 'view_report'
  get 'authority_view', to: 'users#authority_view', as: 'authority_view'

  get 'search', to: 'homes#search', as:'search'
  get 'advance_search', to: 'homes#advance_search', as:'advance_search'
  
  get 'upload_car', to: 'cars#upload_car', as: 'upload_car'
  post 'upload_car', to: 'cars#upload_car_form', as: 'upload_car_form'

  post 'rate_this_seller', to: 'cars#rate_this_seller', as: 'rate_this_seller'
  post 'mark_as_sold', to: 'cars#mark_as_sold', as:'mark_as_sold'

end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id          :bigint           not null, primary key
#  bought      :integer          default(0)
#  description :text
#  make        :string
#  mileage     :integer
#  model       :string
#  photo       :string
#  price       :integer
#  sold        :integer          default(0)
#  year        :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_cars_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Car < ApplicationRecord
    has_one_attached :image
    has_many :saved_cars, dependent: :destroy
    belongs_to :user

    after_commit :add_default_car_image, on: [:create, :update]

    validates :make, presence: true
    validates :year, presence: true
    validates :model, presence: true
    validates :mileage, presence: true
    validates :price, presence: true
    validate :year_must_be_valid
    validate :price_mileage_cannot_be_negative

    def year_must_be_valid
        if !year.nil? and (year > Date.today.year or year < 1900)
            errors.add(:year, ": must be between 1900 and current year")
        end
    end

    def price_mileage_cannot_be_negative
        if !price.nil? and price < 0
            errors.add(:price, ": can't be negative")
        end
        if !mileage.nil? and mileage < 0 
            errors.add(:mileage, ": can't be negative")
        end
    end

    private def add_default_car_image
        unless image.attached?
            self.image.attach(io: File.open(Rails.root.join("app", "assets", "images", "cars", "default-car.jpg")), filename: 'default-car.jpg' , content_type: "image/jpg")
        end
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :car_details]
    def index
        cars = Car.all
        respond_to do |format|
            format.html { render :index, locals: { cars: cars } }
        end
    end 
    
    def car_details
        car_id = params[:id]
        car = Car.find(car_id)
        seller_id = Car.select(:user_id).where(id: car_id)
        seller_id = seller_id[0].user_id
        user_ratings = Rating.where(seller_id: seller_id).sum(:rating)
        totalRater = Rating.select(:id).where(seller_id: seller_id).count
        seller = User.where(id: car.user_id).pluck :name

        ## this section for my ratings for seller
        if user_signed_in?
            myRatingToThisSeller = Rating.select(:rating).where(seller_id: seller_id, buyer_id: current_user.id)
        end
        
        respond_to do |format|
            format.html do
                if totalRater > 0
                    averageRating = user_ratings.to_f/totalRater.to_f
                else
                    averageRating = 0.0
                end
                if user_signed_in? and !myRatingToThisSeller[0].nil? and myRatingToThisSeller[0].rating > 0
                    myRatingToThisSeller = myRatingToThisSeller[0].rating
                else
                    myRatingToThisSeller = 0
                end
                render :index, locals:{car: car, seller: seller, user_rating: averageRating.round, myRating: myRatingToThisSeller}
            end
        end
    end

    def upload_car
        car_data = Car.new
        respond_to do |format|
            format.html { render :upload_car, locals: { car: {}, car_data: car_data } }
        end
    end

    def upload_car_form

        errors = ""
        car_data = Car.new(params.require(:car).permit(:image, :year, :mileage, :model, :make, :description, :price))
    
        respond_to do |format|
            format.html do
                car_data.model = car_data.model.downcase
                car_data.make = car_data.make.downcase
                car_data.user_id = current_user.id

                car_data.model.strip!
                car_data.make.strip!
 
                if car_data.save
                    flash.now[:success] = "Car saved successfully"
                    redirect_to dashboard_url
                else
                    car_data.errors.full_messages.each do |e|
                        errors = errors + e
                    end
                    flash[:error] = car_data.errors.full_messages.join(", ") 
                    render :upload_car, locals: { car_data: car_data }
                end
            end
        end       
    end

    private def upload_image(img)
        File.open(Rails.root.join('app', 'assets', 'images', 'cars', img.original_filename), 'wb') do |f|
            f.write(img.read)
            return img.original_filename
        end
    end

    private def delete_car_image(img)
        path = Rails.root.join('app', 'assets', 'images', 'cars', img)
        if File.exist?(path)
            File.delete(path)
            return true
        else
            return false
        end
    end

    def delete_car
        car = Car.find(params[:id])
        respond_to do |format|
            format.html do
                render :confirm_delete, locals:{car: car}
            end
        end
    end

    def destroy
        car = Car.find(params[:id])

        respond_to do |format|
            format.html do
                if car.destroy
                    flash[:success] = 'Car removed successfully'
                    redirect_to dashboard_url
                else
                    flash[:error] = "Error: cannot delete record" 
                end
            end
        end
    end

    def edit
        car = Car.find(params[:id])
        respond_to do |format|
            format.html do
                render :edit, locals:{car: car}
            end
        end
    end

    def update
        car = Car.find(params[:id])
        

        respond_to do |format|
            format.html do
                if car.update(params.require(:car_edit).permit(:image, :year, :mileage, :model, :make, :description, :price))

                    car.make = car.make.downcase
                    car.make.strip!
                    car.model = car.model.downcase
                    car.model.strip!
                    car.update_attribute(:make, car.make)
                    car.update_attribute(:model, car.model)
                    
                    flash[:success] = "Car updated successfully"
                    redirect_to car_details_url

                else
                    errors = ""
                    car.errors.full_messages.each do |e|
                        errors = errors + e
                    end
                    flash[:error] = car.errors.full_messages.join(", ") 
                    render :edit, locals: { car: car }
                end
            end
        end
    end

    ## this method for seller rating
    def rate_this_seller
        message = nil
        car_id = params[:car_id]
        stars = params[:stars]
        user_id = Car.select(:user_id).where(id: car_id)
        seller_id = user_id[0].user_id
        buyer_id = current_user.id
        isAleadyExist = Rating.where(seller_id: seller_id, buyer_id: buyer_id)
        if !isAleadyExist.empty?
            isAleadyExist[0].update_attribute(:rating, stars)
            message = "Updated!"
        else
            # create a new row
            _newRecord = Rating.new()
            _newRecord.seller_id = seller_id
            _newRecord.buyer_id = buyer_id
            _newRecord.rating = stars
            if _newRecord.save
                message = "Created!"
            else
                message = "Error!"
            end
        end
        render :json => message
    end
    

    def mark_as_sold
        car_id = params[:car_id]
        value = params[:sold]
        car = Car.where(id: car_id)
        car[0].update_attribute(:sold, value)
        render :json => "success"
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/confirm_delete.html.erb
<div class="row">

<div class='col-md-3'></div>
<div class='col-md-6'>
    <form>
        <div class="row title">
            <h1>Delete Car</h1>
        </div>
        <div class="form-row">
            <div class="col-md-8">
                <div class="form-group header">
                    <h4><%=car.make.camelize%> <%= car.model.camelize%></h4>
                </div>

                <div class="form-group">
                    <Strong>Year: </Strong><%= car.year%>
                </div>
                
                <div class="form-group">
                    <Strong>Mileage: </Strong><%= car.mileage%> 
                </div>
                
                <div class="form-group">
                    <Strong>Price: </Strong><%= car.price%> 
                </div>
                <div class="form-group">
                    <Strong>Location: </Strong> Memphis, TN 
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <%= image_tag(car.image, class:'detail_car_size')%>
                </div>
            </div>
        </div>
        <div class="form-row">
            <% if car.description.length > 0 %>
                <div class="form-group">
                    <Strong>Description: </Strong><%= car.description%> 
                </div> 
            <% end %>
        </div>
        <div class="form-row">
            <div class ="form-group">
                <h3 class="text-primary"><strong>Are you sure you want to delete?</strong></h4>
            </div>
            <div class ="form-group">
                <h5 class="text-danger"><strong>*Once deleted, you will not be able to recover this</strong></h4><br>
            </div>
        </div>
        <div class='form-group row'>
                <div class='col-md-4'>
                    <%= link_to 'Yes', '', class:'btn btn-primary btn-decision btn-block', method: :delete %>
                </div>
                <div class='col-md-4'>
                    <%= link_to 'No', car_details_path, class:'btn btn-primary btn-decision btn-block' %>
                </div>
                <div class='col-md-4'>
                    <%= link_to 'Update', update_car_path, class:'btn btn-primary btn-decision btn-block' %>
                </div>
        </div>  
    </form>
</div>
<div class="col-md-3"></div>
</div>

app/views/cars/edit.html.erb
<script>
var loadFile = function(event) {
	var image = document.getElementById('output');
	image.src = URL.createObjectURL(event.target.files[0]);
};
</script>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <h1>Update Car Details</h1>
        <%= form_with model: car, url: car_details_path, multipart: true, method: :patch, local: true, scope: :car_edit do |f| %>  
            <div class="form-row">
                
                <div class="col-md-8">
                
                    <div class="form-group">
                        <%= f.label "make" %>
                        <%= f.text_field "make", :class => 'form-control', required: true %>
                    </div>

                    <div class="form-group">
                        <%= f.label "model" %>
                        <%= f.text_field "model", :class => 'form-control', required: true  %>
                    </div>

                    <div class="form-group">
                        <%= f.label "year" %>
                        <%= f.number_field "year", :class => 'form-control', required: true  %>
                    </div>
                    
                    <div class="form-group">
                        <%= f.label "mileage" %>
                        <%= f.number_field "mileage", :class => 'form-control', required: true %>
                    </div>
                    
                    <div class="form-group">
                        <%= f.label "price" %>
                        <%= f.number_field "price", :class => 'form-control', required: true %>
                    </div>
                    <div class="form-group">
                        <%= f.label "description" %><br />
                        <%= f.text_area "description", size: "5x5" , :class => 'form-control' %>
                    </div>
                    <div class="form-group row">
                    <div class="col-md-6">
                        <%= f.submit "Confirm", :class=>"btn btn-primary btn-block"%>
                    </div>
                    <div class="col-md-6">
                        <%= link_to 'Cancel', dashboard_path, :class=> "btn btn-danger btn-block" %>
                    </div>
                </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                            <%= image_tag(car.image, :id => "output",
                            class:'detail_car_size') %><br>

                            <%= f.file_field :image, 
                            :onchange => "loadFile(event)" %>
                            
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="col-md-1"></div>
</div>

app/views/cars/index.html.erb
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
            <div class="form-row title" >
                <h1><strong>Car Details</strong></h1>
            </div>
            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">
                        <h4><%=car.make.camelize %> <%= car.model.camelize%>  </h4>
                    </div>
                </div>
                <div class="col-md-3">
                    <% if user_signed_in? and car.user_id != current_user.id %>
                        <div class="form-group">
                            <i class="fa fa-heart fa-3x" style="color:#E74C3C;"
                            id="favorite"
                            ></i>
                        </div>
                    <% end %>
                </div>
                <div class="col d-flex justify-content-end">
                        <div class="form-group">
                            <% if user_signed_in? and car.user_id == current_user.id %>
                                <h6>Your Rating</h6>
                            <% else %>
                                <h6>Seller Rating</h6>
                            <% end %>

                            <%for i in 0...user_rating %>
                                <i class="fa fa-star" aria-hidden="true" style="color:red"></i>
                            <% end %>
                            <%for i in 0...(5-user_rating) %>
                            <i class="fa fa-star-o" aria-hidden="true" style="color:red"></i>
                            <%end%>
                        </div>
                </div>
            </div>

            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">
                        <%= image_tag(car.image,class:'detail_car_size') %>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <Strong>Year:</Strong><%= car.year%>
                    </div>
                    
                    <div class="form-group">
                        <Strong>Mileage: </Strong><%= car.mileage%> 
                    </div>
                    
                    <div class="form-group">
                        <Strong>Price: </Strong><%= car.price%> 
                    </div>
                </div>
                <div class="col-md-1"></div>
            </div>

            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">
                        <Strong>Seller: </Strong><%= seller[0] %> 
                    </div>
                    
                    <div class="form-group">
                        <Strong>Location: </Strong> Memphis, TN 
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <% if user_signed_in? and car.user_id == current_user.id%>
                            <input type="checkbox" name="sold" id="mark_as_sold" <%= car.sold == 1? "checked":"" %> data-car_id=<%= car.id%> />
                        <% else %>
                            <input type="checkbox" name="sold"  <%= car.sold == 1? "checked":"" %> disabled/>
                        <% end %>
                        <span><strong class="text-primary">Sold</strong></span>
                    </div>
                </div>
                <div class="col d-flex justify-content-end">
                    <% if user_signed_in? and car.user_id != current_user.id %>
                        <div class="form-group">
                            <h6>Rate this seller</h6>
                            <span class="star-rating" style="hidden:true" data-star="0" data-car_id= "<%= car.id%>"> <i class="fa" ></i> </span>
                            <%(1..myRating).each do |i|%>
                                <span class="star-rating" data-star="<%= i %>" data-car_id= "<%= car.id%>"> <i class="fa fa-star" id="car_id_<%= i%>" style="color:red"></i> </span>
                            <%end%>
                            <%(myRating+1..5).each do |i|%>
                                <span class="star-rating" data-star="<%= i %>" data-car_id= "<%= car.id%>"> <i class="fa fa-star-o" id="car_id_<%= i%>" style="color:red"></i> </span>
                            <%end%>
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-12">
                    <% if car.description.length > 0 %>
                        <div class="form-group">
                            <Strong>Description:</Strong><%= car.description%> 
                        </div>
                    <% end %>
                </div>
            </div>
            <div class="row">
                    <% if user_signed_in? %>
                        <% if current_user.id == car.user_id %>
                            <div class="col-sm-2"></div>
                            <div class="col-sm-3">
                                <%= link_to 'Update Car', update_car_path, :class=>"btn btn-primary btn-block" %>
                            </div>
                            
                            <div class="col-sm-1"></div>
                            <div class="col-sm-3">
                                <%= link_to 'Delete Car', delete_car_path, :class=> "btn btn-danger btn-block" %>
                            </div>
                            <div class="col-sm-2"></div>
                        <% else %>
                            <div class="col-sm-4"></div>
                            <div class="col-sm-4">
                                <%= link_to 'Send Message', new_conversation_path(car), :class=>"btn btn-primary btn-block" %>
                            </div>
                            <div class="col-sm-4"></div>
                            <div style="display: none;">
                                <%= link_to 'Save Car', saved_car_path, :class=>"btn btn-primary btn-block", :id => "save_car" %>
                            </div>
                        <% end %>
                    <% end %>
            </div>
    </div>
    </div>
    <div class="col-md-1"></div>
</div>

app/views/cars/upload_car.html.erb
<script>
var upload_file = function(event){
    var file = document.getElementById("upload_image");
    file.click();

};
var loadFile = function(event) {
	var image = document.getElementById('output');
	image.src = URL.createObjectURL(event.target.files[0]);
};
</script>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <h1>Let's add some details...</h1>
        <%= form_with model: car_data, url: upload_car_form_path, multipart: true, method: :post, local: true, scope: :car do |f| %>  
            <div class="form-row">
                
                <div class="col-md-8">
                
                    <div class="form-group">
                        <%= f.label "make" %>
                        <%= f.text_field "make", :class => 'form-control', required: true %>
                    </div>

                    <div class="form-group">
                        <%= f.label "model" %>
                        <%= f.text_field "model", :class => 'form-control', required: true  %>
                    </div>

                    <div class="form-group">
                        <%= f.label "year" %>
                        <%= f.number_field "year", :class => 'form-control', required: true  %>
                    </div>
                    
                    <div class="form-group">
                        <%= f.label "mileage" %>
                        <%= f.number_field "mileage", :class => 'form-control', required: true %>
                    </div>
                    
                    <div class="form-group">
                        <%= f.label "price" %>
                        <%= f.number_field "price", :class => 'form-control', required: true %>
                    </div>
                    <div class="form-group">
                        <%= f.label "description" %><br />
                        <%= f.text_area "description", size: "5x2" , :class => 'form-control' %>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6">
                            <%= f.submit "Confirm", :class=>"btn btn-primary btn-block"%>
                        </div>
                        <div class="col-md-6">
                            <%= link_to 'Cancel', dashboard_path, :class=> "btn btn-danger btn-block" %>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <%= image_tag 'upload_image.png', :id => "output", :onclick => "upload_file(event)", class:'detail_car_size'%>
                        <%= f.file_field :image, :onchange => "loadFile(event)", :id => "upload_image", :style => "display: none;" %>  

                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="col-md-1"></div>
</div>