config/routes.rb
Rails.application.routes.draw do

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  
  get 'favorite_car', to: 'saved_cars#favorite_car', as: 'favorite_car'
  get 'car_details/:id/saved_car', to: 'saved_cars#save_car', as: 'saved_car'
  get 'about', to: 'homes#about', as: 'about'


  root to: 'homes#welcome'
  get 'dashboard', to: 'dashboards#dashboard', as:'dashboard'
  get 'profile', to: 'users#profile', as: 'profile'  # profile
  get 'home', to: 'homes#welcome', as:'home'
  #get 'car_details', to: 'cars#index', as: 'car_details' # car details
  get 'car_details/:id', to: 'cars#car_details', as:'car_details'

  get 'car_details/:id/edit', to: 'cars#edit', as: 'update_car'
  put 'car_details/:id', to: 'cars#update' # update (put)
  patch 'car_details/:id', to: 'cars#update' # update (patch)

  # Navid
  # get 'users/:id/edit_password', to: 'users#edit_password', as: 'change_password' # edit
  # patch 'users/:id', to: 'users#update_password' # update (as needed)
  # put 'users/:id', to: 'users#update_password' # update (full replacement)

  # Hosneara: added routes for delete car # 
  get 'car_details/:id/confirm_delete', to: 'cars#delete_car', as: 'delete_car'
  delete 'car_details/:id/confirm_delete', to: 'cars#destroy'
  #get 'car_details/:id/delete_car_image', to: 'cars#delete_car_image', as: 'delete_car_image'
  
  get 'send_message_to_seller/:id', to: 'conversations#send_message_to_seller', as:'send_message_to_seller'
  get 'send_message', to: 'conversations#index', as: 'send_message'
  get 'notification/:id', to: 'notifications#show', as: 'notification'

  get 'new_conversation/:id', to: 'conversations#new_conversation', as: 'new_conversation'

  post 'new_message', to: 'messages#new_message', as: 'new_message'

  get 'report', to: 'users#report', as: 'report'
  post 'report', to: 'users#report_authority', as: 'report_authority'
  get 'view_report', to: 'users#index', as: 'view_report'
  get 'authority_view', to: 'users#authority_view', as: 'authority_view'

  get 'search', to: 'homes#search', as:'search'
  get 'advance_search', to: 'homes#advance_search', as:'advance_search'
  
  get 'upload_car', to: 'cars#upload_car', as: 'upload_car'
  post 'upload_car', to: 'cars#upload_car_form', as: 'upload_car_form'

  post 'rate_this_seller', to: 'cars#rate_this_seller', as: 'rate_this_seller'
  post 'mark_as_sold', to: 'cars#mark_as_sold', as:'mark_as_sold'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiger-Car-App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Tiger-Car-App', root_path, class:'navbar-brand font-weight-bold text-primary'  %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'About', about_path, :class=>"nav-link font-weight-bold text-info" %>
          </li>
        </ul>

        <ul class="navbar-nav">
          <% if !user_signed_in? %>
            
            <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, :class=>"nav-link font-weight-bold text-info" %>
            </li>
            <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, :class=>"nav-link font-weight-bold text-info" %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <%= render 'notifications/notification_dropdown' %>
          <li class="nav-item">
            <%= link_to dashboard_path, class:'nav-link' do %>
              <i class="fa fa-dashboard fa-2x" style="color:blue !important"> </i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to image_tag(current_user.photo, class:'round-circle profile_picture'), profile_path, class:'nav-link' %>
            
          </li>
          <%end%>
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
              <a class="btn btn-lg dropdown-toggle " href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.name %></a>
              <div class="dropdown-menu dropdown-menu-right">
                <%= link_to "Profile", profile_path, :class => "dropdown-item" %>
                <%= link_to "Saved Car", favorite_car_path, :class => "dropdown-item" %>
                <%= link_to "Sell Car", upload_car_path, :class => "dropdown-item" %>
                <%= link_to "Send Message", send_message_path, :class => "dropdown-item" %>
                <%= link_to "Report Authority", report_path, :class => "dropdown-item" %>
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class=>"dropdown-item font-weight-bold text-danger" %>
              </div>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <% flash.each do |type, msg| %>
        <div class="alert alert-<%=type%>">
          <%= msg %>
        </div>
    <% end %>
    
    <main class="container">
      <%-# code for devise -%>
      <%-#<p class="notice"><%= notice </p>%>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>

  </body>
</html>